package com.cooksys.fastbook.models;

// Generated May 5, 2016 8:24:55 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendId generated by hbm2java
 */
@Embeddable
public class FriendId implements java.io.Serializable {

	private int sentId;
	private int receivedId;

	public FriendId()
	{
	}

	public FriendId(int sentId, int receivedId)
	{
		this.sentId = sentId;
		this.receivedId = receivedId;
	}

	@Column(name = "sent_id", nullable = false)
	public int getSentId()
	{
		return this.sentId;
	}

	public void setSentId(int sentId)
	{
		this.sentId = sentId;
	}

	@Column(name = "received_id", nullable = false)
	public int getReceivedId()
	{
		return this.receivedId;
	}

	public void setReceivedId(int receivedId)
	{
		this.receivedId = receivedId;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FriendId))
			return false;
		FriendId castOther = (FriendId) other;

		return (this.getSentId() == castOther.getSentId())
				&& (this.getReceivedId() == castOther.getReceivedId());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getSentId();
		result = 37 * result + this.getReceivedId();
		return result;
	}

}
