package com.cooksys.fastbook.models;

// Generated May 3, 2016 2:05:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendId generated by hbm2java
 */
@Embeddable
public class FriendId implements java.io.Serializable {

	private int receivedId;
	private int sentId;

	public FriendId()
	{
	}

	public FriendId(int receivedId, int sentId)
	{
		this.receivedId = receivedId;
		this.sentId = sentId;
	}

	@Column(name = "received_id", nullable = false)
	public int getReceivedId()
	{
		return this.receivedId;
	}

	public void setReceivedId(int receivedId)
	{
		this.receivedId = receivedId;
	}

	@Column(name = "sent_id", nullable = false)
	public int getSentId()
	{
		return this.sentId;
	}

	public void setSentId(int sentId)
	{
		this.sentId = sentId;
	}

}
