package com.cooksys.fastbook.models;

// Generated May 4, 2016 2:37:24 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupUser generated by hbm2java
 */
@Entity
@Table(name = "group_user", catalog = "fastbook")
public class GroupUser implements java.io.Serializable {

	private Integer id;
	private Group group;
	private User user;

	public GroupUser()
	{
	}

	public GroupUser(Group group, User user)
	{
		this.group = group;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false)
	public Group getGroup()
	{
		return this.group;
	}

	public void setGroup(Group group)
	{
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser()
	{
		return this.user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

}
