package com.cooksys.fastbook.models;

// Generated May 5, 2016 8:24:55 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupUserId generated by hbm2java
 */
@Embeddable
public class GroupUserId implements java.io.Serializable {

	private int groupId;
	private int userId;

	public GroupUserId()
	{
	}

	public GroupUserId(int groupId, int userId)
	{
		this.groupId = groupId;
		this.userId = userId;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId()
	{
		return this.groupId;
	}

	public void setGroupId(int groupId)
	{
		this.groupId = groupId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId()
	{
		return this.userId;
	}

	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupUserId))
			return false;
		GroupUserId castOther = (GroupUserId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
