package com.cooksys.fastbook.models;

// Generated May 5, 2016 8:24:55 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupUser generated by hbm2java
 */
@Entity
@Table(name = "group_user", catalog = "fastbook")
public class GroupUser implements java.io.Serializable {

	private GroupUserId id;
	private Group group;
	private User user;
	private Boolean owner;

	public GroupUser()
	{
	}

	public GroupUser(GroupUserId id, Group group, User user)
	{
		this.id = id;
		this.group = group;
		this.user = user;
	}

	public GroupUser(GroupUserId id, Group group, User user, Boolean owner)
	{
		this.id = id;
		this.group = group;
		this.user = user;
		this.owner = owner;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public GroupUserId getId()
	{
		return this.id;
	}

	public void setId(GroupUserId id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "group_id", nullable = false, insertable = false, updatable = false)
	public Group getGroup()
	{
		return this.group;
	}

	public void setGroup(Group group)
	{
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser()
	{
		return this.user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

	@Column(name = "owner")
	public Boolean getOwner()
	{
		return this.owner;
	}

	public void setOwner(Boolean owner)
	{
		this.owner = owner;
	}

}
