package com.cooksys.fastbook.models;

// Generated May 5, 2016 8:24:55 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name = "group", catalog = "fastbook")
public class Group implements java.io.Serializable {

	private Integer id;
	private String name;
	
	@JsonIgnore
	private Set<Post> posts = new HashSet<Post>(0);
	
	@JsonIgnore
	private Set<GroupUser> groupUsers = new HashSet<GroupUser>(0);

	public Group()
	{
	}

	public Group(String name)
	{
		this.name = name;
	}

	public Group(String name, Set<Post> posts, Set<GroupUser> groupUsers)
	{
		this.name = name;
		this.posts = posts;
		this.groupUsers = groupUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "post_group", catalog = "fastbook", joinColumns = { @JoinColumn(name = "group_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "post_id", nullable = false, updatable = false) })
	public Set<Post> getPosts()
	{
		return this.posts;
	}

	public void setPosts(Set<Post> posts)
	{
		this.posts = posts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "group")
	public Set<GroupUser> getGroupUsers()
	{
		return this.groupUsers;
	}

	public void setGroupUsers(Set<GroupUser> groupUsers)
	{
		this.groupUsers = groupUsers;
	}

}
