package com.cooksys.fastbook.models;

// Generated May 4, 2016 2:37:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name = "post", catalog = "fastbook")
public class Post implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private User user;
	private String text;
	private int author;
	private Set<PostUser> postUsers = new HashSet<PostUser>(0);
	private Set<PostGroup> postGroups = new HashSet<PostGroup>(0);

	public Post()
	{
	}

	public Post(User user, String text, int author)
	{
		this.user = user;
		this.text = text;
		this.author = author;
	}

	public Post(User user, String text, int author, Set<PostUser> postUsers,
			Set<PostGroup> postGroups)
	{
		this.user = user;
		this.text = text;
		this.author = author;
		this.postUsers = postUsers;
		this.postGroups = postGroups;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp()
	{
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp)
	{
		this.timestamp = timestamp;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser()
	{
		return this.user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

	@Column(name = "text", nullable = false, length = 140)
	public String getText()
	{
		return this.text;
	}

	public void setText(String text)
	{
		this.text = text;
	}

	@Column(name = "author", nullable = false)
	public int getAuthor()
	{
		return this.author;
	}

	public void setAuthor(int author)
	{
		this.author = author;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "post")
	public Set<PostUser> getPostUsers()
	{
		return this.postUsers;
	}

	public void setPostUsers(Set<PostUser> postUsers)
	{
		this.postUsers = postUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "post")
	public Set<PostGroup> getPostGroups()
	{
		return this.postGroups;
	}

	public void setPostGroups(Set<PostGroup> postGroups)
	{
		this.postGroups = postGroups;
	}

}
