package com.cooksys.fastbook.models;

// Generated May 5, 2016 8:24:55 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name = "post", catalog = "fastbook")
public class Post implements java.io.Serializable {

	private Integer id;
	private Date timestamp;
	private User user;
	private String text;
	
	@JsonIgnore
	private Set<User> users = new HashSet<User>(0);
	
	@JsonIgnore
	private Set<Group> groups = new HashSet<Group>(0);
	
	@JsonIgnore
	private Set<Like> likes = new HashSet<Like>(0);

	public Post()
	{
	}

	public Post(User user, String text)
	{
		this.user = user;
		this.text = text;
	}

	public Post(User user, String text, Set<User> users, Set<Group> groups,
			Set<Like> likes)
	{
		this.user = user;
		this.text = text;
		this.users = users;
		this.groups = groups;
		this.likes = likes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19)
	public Date getTimestamp()
	{
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp)
	{
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "author", nullable = false)
	public User getUser()
	{
		return this.user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

	@Column(name = "text", nullable = false, length = 140)
	public String getText()
	{
		return this.text;
	}

	public void setText(String text)
	{
		this.text = text;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "post_user", catalog = "fastbook", joinColumns = { @JoinColumn(name = "post_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<User> getUsers()
	{
		return this.users;
	}

	public void setUsers(Set<User> users)
	{
		this.users = users;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "post_group", catalog = "fastbook", joinColumns = { @JoinColumn(name = "post_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "group_id", nullable = false, updatable = false) })
	public Set<Group> getGroups()
	{
		return this.groups;
	}

	public void setGroups(Set<Group> groups)
	{
		this.groups = groups;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "like_post", catalog = "fastbook", joinColumns = { @JoinColumn(name = "post_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "like_id", nullable = false, updatable = false) })
	public Set<Like> getLikes()
	{
		return this.likes;
	}

	public void setLikes(Set<Like> likes)
	{
		this.likes = likes;
	}

}
