package com.cooksys.fastbook.models;

// Generated May 4, 2016 2:37:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "fastbook")
public class User implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private Date birthDate;
	private Date joinDate;
	private Set<Friend> friendsForSentId = new HashSet<Friend>(0);
	private Set<Friend> friendsForReceivedId = new HashSet<Friend>(0);
	private Group group;
	private Set<GroupUser> groupUsers = new HashSet<GroupUser>(0);
	private Set<PostUser> postUsers = new HashSet<PostUser>(0);
	private Post post;

	public User()
	{
	}

	public User(String firstName, String lastName, String email,
			String password, Date birthDate, Date joinDate)
	{
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.birthDate = birthDate;
		this.joinDate = joinDate;
	}

	public User(String firstName, String lastName, String email,
			String password, Date birthDate, Date joinDate,
			Set<Friend> friendsForSentId, Set<Friend> friendsForReceivedId,
			Group group, Set<GroupUser> groupUsers, Set<PostUser> postUsers,
			Post post)
	{
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.birthDate = birthDate;
		this.joinDate = joinDate;
		this.friendsForSentId = friendsForSentId;
		this.friendsForReceivedId = friendsForReceivedId;
		this.group = group;
		this.groupUsers = groupUsers;
		this.postUsers = postUsers;
		this.post = post;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName()
	{
		return this.firstName;
	}

	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName()
	{
		return this.lastName;
	}

	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", nullable = false, length = 10)
	public Date getBirthDate()
	{
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate)
	{
		this.birthDate = birthDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "join_date", nullable = false, length = 19)
	public Date getJoinDate()
	{
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate)
	{
		this.joinDate = joinDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userBySentId")
	public Set<Friend> getFriendsForSentId()
	{
		return this.friendsForSentId;
	}

	public void setFriendsForSentId(Set<Friend> friendsForSentId)
	{
		this.friendsForSentId = friendsForSentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByReceivedId")
	public Set<Friend> getFriendsForReceivedId()
	{
		return this.friendsForReceivedId;
	}

	public void setFriendsForReceivedId(Set<Friend> friendsForReceivedId)
	{
		this.friendsForReceivedId = friendsForReceivedId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public Group getGroup()
	{
		return this.group;
	}

	public void setGroup(Group group)
	{
		this.group = group;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<GroupUser> getGroupUsers()
	{
		return this.groupUsers;
	}

	public void setGroupUsers(Set<GroupUser> groupUsers)
	{
		this.groupUsers = groupUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<PostUser> getPostUsers()
	{
		return this.postUsers;
	}

	public void setPostUsers(Set<PostUser> postUsers)
	{
		this.postUsers = postUsers;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public Post getPost()
	{
		return this.post;
	}

	public void setPost(Post post)
	{
		this.post = post;
	}

}
