package com.cooksys.fastbook.models;
// Generated May 2, 2016 5:21:13 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "fastbook")
public class User implements java.io.Serializable
{

	private Integer id;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private Date birthDate;
	private Date joinDate;
	
	@JsonIgnore
	private Set<Friend> friendsForSentId = new HashSet<Friend>(0);
	
	@JsonIgnore
	private Set<Friend> friendsForReceivedId = new HashSet<Friend>(0);

	public User()
	{
	}

	public User(String firstName, String lastName, String email, String password, Date birthDate, Date joinDate)
	{
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.birthDate = birthDate;
		this.joinDate = joinDate;
	}

	public User(String firstName, String lastName, String email, String password, Date birthDate, Date joinDate,
			Set<Friend> friendsForSentId, Set<Friend> friendsForReceivedId)
	{
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.birthDate = birthDate;
		this.joinDate = joinDate;
		this.friendsForSentId = friendsForSentId;
		this.friendsForReceivedId = friendsForReceivedId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName()
	{
		return this.firstName;
	}

	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName()
	{
		return this.lastName;
	}

	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_date", nullable = false, length = 10)
	public Date getBirthDate()
	{
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate)
	{
		this.birthDate = birthDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "join_date", nullable = false, length = 10)
	public Date getJoinDate()
	{
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate)
	{
		this.joinDate = joinDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userBySentId")
	public Set<Friend> getFriendsForSentId()
	{
		return this.friendsForSentId;
	}

	public void setFriendsForSentId(Set<Friend> friendsForSentId)
	{
		this.friendsForSentId = friendsForSentId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByReceivedId")
	public Set<Friend> getFriendsForReceivedId()
	{
		return this.friendsForReceivedId;
	}

	public void setFriendsForReceivedId(Set<Friend> friendsForReceivedId)
	{
		this.friendsForReceivedId = friendsForReceivedId;
	}

}
